server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /auth {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    location /info {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    location /config {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    location /download-jobs {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_buffering off;
        proxy_read_timeout 300s;
    }

    location /download {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_buffering off;
        proxy_read_timeout 300s;
    }
}
